POST http://localhost:5000/api/Employees
Content-Type: application/json
Accept: application/json

{
  "title": "Developer",
  "firstName": "John",
  "lastName": "Doe",
  "phone": "+421123456789",
  "email": "john.doe@example.com"
}
